### rest http test file

### login by username
# the default login user is `/users/sessions`
POST http://localhost:8080/users/sessions
Content-Type: application/x-www-form-urlencoded

username=user&password=user

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

### visit hello api
GET http://localhost:8080/hello
Authorization: {{auth_token}}

###
